### PR TITLE
Add support for Hybrid attributes

### PR DESCRIPTION
**Pull request by juliotrigo**
* Add support for Hybrid attributes: filtering and sorting
  * Hybrid properties
  * Hybrid methods

This addresses this issue #22 and is the continuation of the work started here #32

### CODE REVIEW

**Comment by juliotrigo** [comment]
@mattbennett @timbu @iky , another one for you guys to take a look at if any of you has a spare moment to spend. I would really appreciate it :)

**Comment by juliotrigo** [comment]
Updated with `master` and release notes.

**Comment by kevgliss** [comment]
Any chance we could get a release published with these changes?

**Comment by juliotrigo** [comment]
@kevgliss https://github.com/juliotrigo/sqlalchemy-filters/releases/tag/v0.12.0 has just been released, which includes these changes.

**Pull request merged**
