### PR TITLE
Support for SQLAlchemy 1.4

### PR DESCRIPTION
**Pull request by bodik**
Based on https://github.com/juliotrigo/sqlalchemy-filters/pull/64 and https://github.com/juliotrigo/sqlalchemy-filters/pull/68 I've elaborated on Sqlalchemy 1.4 backward compatible support

### CODE REVIEW

**Review by munkien — APPROVED** [review]
Works in my test environment!

**Comment by pcasa** [comment]
Is there anything blocking this PR?  Would love to upgrade Sqlalchemy.

**Comment by kinlamleung** [comment]
This package hasn't been updated for a long time, we have projects with this tool and planned to upgrade sqlalchemy to 1.4. 

Any plan to release a new version?  We may need to drop out this dependency if no plan on the support SA 1.4.  Thanks.

**Comment by pcasa** [comment]
> This package hasn't been updated for a long time, we have projects with this tool and planned to upgrade sqlalchemy to 1.4.
> 
> Any plan to release a new version? We may need to drop out this dependency if no plan on the support SA 1.4. Thanks.

We are on the same situation.

**Comment by bodik** [comment]
either we can try to reach @juliotrigo via some other means that github and ask for maitainers permissions or fork the project under new name ;/

**Comment by bodik** [comment]
FYI https://github.com/juliotrigo/sqlalchemy-filters/issues/72

**Comment by LyleScott** [comment]
This is open source, you just fork and move on IMHO. No need for permission.

**Comment by bodik** [comment]
> This is open source, you just fork and move on IMHO. No need for permission.

but with permission we might be able to continue under same package name on pypi

**Comment by hereischen** [comment]
After about 1 month, I think create a new package on pypi would be better than waiting @bodik

**Review by dheeraj-freaqo — APPROVED** [review]

**Comment by mvilanova** [comment]
Has anyone tried this alternative https://github.com/elmkarami/sqlalchemy-filters-plus, which has support for SQLAlchemy 1.4?

**Comment by hereischen** [comment]
> Has anyone tried this alternative https://github.com/elmkarami/sqlalchemy-filters-plus, which has support for SQLAlchemy 1.4?

This one works

**Pull request merged**
