### PR TITLE
Fix for SQLAlchemy 1.4

### PR DESCRIPTION
**Pull request by nanocfw**
Fix for SQLAlchemy 1.4

### CODE REVIEW

**Comment by nanocfw** [comment]
Need version of sqlalchemy_utils with pull https://github.com/kvesteri/sqlalchemy-utils/pull/506

**Comment by pcasa** [comment]
Would really like to see if this project could support sqlalchemy 1.4.

**Comment by jkolaric** [comment]
Raising the sqlalchemy_utils version to 0.37.0 would result in this library being incompatible with py27 since sqlalchemy_utils did remove the py27 refs in version 0.36.7

https://github.com/kvesteri/sqlalchemy-utils/commit/b43140eeca2630fc893c3e9d8a984cf97538ea68#diff-2adaa5152ab060d04b18f4afdf78174e

**Comment by pcasa** [comment]
py 2.7 EOL was on JAN 2020, over a year ago now.
As much as I would like to continue supporting this version as well, we should consider moving forward.  Security patches being a concern.  Official 2.7 is not getting them anymore.

**Comment by davidjb99** [comment]
would be great to get this merged

**Comment by bodik** [comment]
> would be great to get this merged

you should not expect some patch to be merged if it fails CI

**Comment by pcasa** [comment]
Couple of things.
Some of the fails is on generating coverage reports.
Builds for Python < 3.X will fail with this upgrade.
The main error seems to be coming from https://docs.sqlalchemy.org/en/14/changelog/migration_13.html#key-behavioral-changes-orm

**Comment by nanocfw** [comment]
Please consider merge pull #69.

**Pull request closed without merging**
